# Generated by Django 5.2.4 on 2025-07-23 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='kms_driven',
            field=models.PositiveIntegerField(default=0, help_text='Kilometers driven'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='image',
            field=models.ImageField(default='car_images/default.png', upload_to='car_images/', verbose_name='Main Image'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/additional/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='listings.carlisting')),
            ],
        ),
    ]
