# Generated by Django 5.2.4 on 2025-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_carlisting_kms_driven_alter_carlisting_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='kms_driven',
            field=models.PositiveIntegerField(default=0, help_text='Kilometers driven'),
        ),
    ]
