# Generated by Django 5.2.4 on 2025-07-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_carlisting_views_alter_carlisting_kms_driven'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seller_response',
            field=models.TextField(blank=True, null=True, verbose_name="Seller's Response"),
        ),
    ]
